spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket?serverTimezone=CST&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: adsl39547
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 553907370@qq.com
    password: xikcjwbybrcnbedc
    protocol: smtp
    default-encoding: utf-8

#  mysql -u root -p
#  set global time_zone='+8:00';

server:
  port: 8088

#控制台打印sql语句
mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5